name: Run Python Script Daily

on:
  schedule:
    # Run daily at 12:00 AM UTC
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Upgrade pip and install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 PyGithub

      # Step 4: Log installed packages for debugging
      - name: List installed packages
        run: pip list

      # Step 5: Run your Python script
      - name: Run script
        run: python sk.py
